// <auto-generated />
using System;
using System.Collections.Generic;
using Auth.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Auth.Infrastructure.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auth.Domain.Aggregates.LoginRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("MagicLinkTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("magic_link_token_hash");

                    b.Property<string>("OtpTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("otp_token_hash");

                    b.Property<string>("TokenKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("token_key");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Fingerprint", "Auth.Domain.Aggregates.LoginRequest.Fingerprint#Fingerprint", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ComputedHash")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_computed_hash");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_ip_address");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_language");

                            b1.Property<string>("NormalizedBrowser")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_normalized_browser");

                            b1.Property<string>("NormalizedOs")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_normalized_os");

                            b1.Property<string>("Timezone")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_timezone");

                            b1.Property<string>("UserAgent")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_user_agent");
                        });

                    b.HasKey("Id")
                        .HasName("pk_login_requests");

                    b.HasIndex("ConsumedAt")
                        .HasDatabaseName("ix_login_requests_consumed_at");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_login_requests_expires_at");

                    b.HasIndex("TokenKey")
                        .IsUnique()
                        .HasDatabaseName("ix_login_requests_token_key");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_login_requests_user_id");

                    b.HasIndex("TokenKey", "ConsumedAt", "ExpiresAt")
                        .HasDatabaseName("ix_login_requests_token_key_consumed_at_expires_at");

                    b.ToTable("login_requests", (string)null);
                });

            modelBuilder.Entity("Auth.Domain.Aggregates.RecoveryKeyChain", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastRotatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_rotated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_recovery_key_chains");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_recovery_key_chains_created_at");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_recovery_key_chains_user_id");

                    b.ToTable("recovery_key_chains", (string)null);
                });

            modelBuilder.Entity("Auth.Domain.Aggregates.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("LastRefreshedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_refreshed_at");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("refresh_token_hash");

                    b.Property<string>("RefreshTokenKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("refresh_token_key");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Fingerprint", "Auth.Domain.Aggregates.Session.Fingerprint#Fingerprint", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ComputedHash")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_computed_hash");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_ip_address");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_language");

                            b1.Property<string>("NormalizedBrowser")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_normalized_browser");

                            b1.Property<string>("NormalizedOs")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_normalized_os");

                            b1.Property<string>("Timezone")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_timezone");

                            b1.Property<string>("UserAgent")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_user_agent");
                        });

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_sessions_expires_at");

                    b.HasIndex("RefreshTokenKey")
                        .IsUnique()
                        .HasDatabaseName("ix_sessions_refresh_token_key");

                    b.HasIndex("RevokedAt")
                        .HasDatabaseName("ix_sessions_revoked_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.HasIndex("ExpiresAt", "RevokedAt")
                        .HasDatabaseName("ix_sessions_expires_at_revoked_at");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("ix_sessions_user_id_revoked_at");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Auth.Domain.Aggregates.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarKey")
                        .HasColumnType("varchar")
                        .HasColumnName("avatar_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasColumnName("display_name");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("email_address");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_users_created_at");

                    b.HasIndex("EmailAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_address");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("ix_users_is_verified");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Auth.Domain.Entities.RecoveryKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("identifier");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<Guid>("RecoveryKeyChainId")
                        .HasColumnType("uuid")
                        .HasColumnName("recovery_key_chain_id");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("used_at");

                    b.Property<string>("VerifierHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasColumnName("verifier_hash");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Fingerprint", "Auth.Domain.Entities.RecoveryKey.Fingerprint#Fingerprint", b1 =>
                        {
                            b1.Property<string>("ComputedHash")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_computed_hash");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_ip_address");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_language");

                            b1.Property<string>("NormalizedBrowser")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_normalized_browser");

                            b1.Property<string>("NormalizedOs")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_normalized_os");

                            b1.Property<string>("Timezone")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_timezone");

                            b1.Property<string>("UserAgent")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar")
                                .HasColumnName("fingerprint_user_agent");
                        });

                    b.HasKey("Id")
                        .HasName("pk_recovery_keys");

                    b.HasIndex("Identifier")
                        .HasDatabaseName("ix_recovery_keys_identifier");

                    b.HasIndex("IsUsed")
                        .HasDatabaseName("ix_recovery_keys_is_used");

                    b.HasIndex("RecoveryKeyChainId")
                        .HasDatabaseName("ix_recovery_keys_recovery_key_chain_id");

                    b.HasIndex("Identifier", "IsUsed")
                        .HasDatabaseName("ix_recovery_keys_identifier_is_used");

                    b.HasIndex("RecoveryKeyChainId", "IsUsed")
                        .HasDatabaseName("ix_recovery_keys_recovery_key_chain_id_is_used");

                    b.ToTable("recovery_keys", (string)null);
                });

            modelBuilder.Entity("Auth.Domain.Entities.RecoveryKey", b =>
                {
                    b.HasOne("Auth.Domain.Aggregates.RecoveryKeyChain", null)
                        .WithMany("RecoveryKeys")
                        .HasForeignKey("RecoveryKeyChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recovery_keys_recovery_key_chains_recovery_key_chain_id");
                });

            modelBuilder.Entity("Auth.Domain.Aggregates.RecoveryKeyChain", b =>
                {
                    b.Navigation("RecoveryKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
